const LOAD_GAMES = "LOAD_GAMES";
const FILTER = "FILTER";
const ORDER = "ORDER";
//const LOAD_GENRES = "LOAD_GENRES";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const LOAD_GAME_BY_ID = "LOAD_GAME_BY_ID";
const FILTER_BY_GENRE = "FILTER_BY_GENRE";
const LOAD_GENRES = "LOAD_GENRES";
const FILTER_BY_SOURCE = "FILTER_BY_SOURCE";
const SET_MODAL = "SET_MODAL";
const FILTER_GAMES_BY_GENRE = "FILTER_GAMES_BY_GENRE";
//Falta paginar

export { 
    LOAD_GAMES, 
    FILTER, 
    ORDER, 
    //LOAD_GENRES, 
    SEARCH_BY_NAME, 
    LOAD_GAME_BY_ID, 
    FILTER_BY_GENRE, 
    LOAD_GENRES,
    FILTER_BY_SOURCE,
    SET_MODAL,
    FILTER_GAMES_BY_GENRE,
};